"""Add is_deleted column to decks and cards

Revision ID: 8ab0c9709ebe
Revises: 
Create Date: 2025-05-22 01:29:16.927233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ab0c9709ebe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('card', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('deck', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('deck', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deck', 'deleted_at')
    op.drop_column('deck', 'is_deleted')
    op.drop_column('card', 'deleted_at')
    op.drop_column('card', 'is_deleted')
    # ### end Alembic commands ###
